# https://hub.docker.com/r/webcenter/activemq/
version: '2'
services:
  activemq:
    build: 
      context: .
      dockerfile: activemq
    image: mageddo/activemq
    container_name: activemq
    hostname: activemq.dev
    network_mode: bridge
    volumes:
      - /opt/queue/activemq/:/data/activemq
      - /var/log/activemq/:/var/log/activemq
      - $PWD/activemq.xml:/opt/activemq/conf/activemq.xml
    environment:
      - ACTIVEMQ_ADMIN_LOGIN=admin
      - ACTIVEMQ_ADMIN_PASSWORD=admin
      - ACTIVEMQ_USER_LOGIN=guest
      - ACTIVEMQ_USER_PASSWORD=guest
      - ACTIVEMQ_NAME=activemq.dev

  activemq-2:
    extends: activemq
    container_name: activemq-2
    hostname: activemq.dev
    volumes:
      - $PWD/activemq-kahab.xml:/opt/activemq/conf/activemq.xml
    environment:
      - ACTIVEMQ_NAME=activemq-2.dev
    ports:
      - 8161:8161
      - 61616:61616

  activemq-node-3:
    extends: activemq
    container_name: activemq-3
    hostname: activemq-3.dev
    volumes:
      - /opt/queue/activemq-3/:/data/activemq
      - /var/log/activemq-3/:/var/log/activemq

# web-console: 8161
# broker: tcp://activemq.dev:61616