FROM java:openjdk-8u91

WORKDIR /h2

ENV H2_VERSION=1.4.193
ENV WEB_PORT=8082
ENV TCP_PORT=9092
ENV BASE_DIR=/h2/data
ENV CONF_DIR=/h2/conf

RUN mkdir -p $BASE_DIR && \
	mkdir -p $CONF_DIR && \
	curl -L http://central.maven.org/maven2/com/h2database/h2/$H2_VERSION/h2-$H2_VERSION.jar > /h2/h2.jar

CMD bash -c "java -cp '/h2/h2.jar' org.h2.tools.Server -web -tcp -trace -webAllowOthers -tcpAllowOthers -webPort $WEB_PORT -tcpPort $TCP_PORT -baseDir $BASE_DIR -properties $CONF_DIR"