# https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
# docker run -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch:5.6.4
version: '2'
services:
  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.4
    container_name: elasticsearch1
    environment:
      # - cluster.name=docker-cluster
      # - bootstrap.memory_lock=true
      - discovery.type=single-node
    volumes:
      - /data/es1/data:/usr/share/elasticsearch/data # it needs permission for others like (777) for tests
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
      - 9300:9300
    hostname: elasticsearch.dev
    mem_limit: 2048m

  kibana:
    image: docker.elastic.co/kibana/kibana:5.6.4
    hostname: kibana.dev
    environment:
      - ELASTICSEARCH_URL=elasticsearch.dev:9200
    volumes:
      - ./elasticsearch/config/kibana.yml:/usr/share/kibana/config/kibana.yml