# https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
# docker run -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch:5.6.4
version: '2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.4
    container_name: elasticsearch1
    environment:
      # - cluster.name=docker-cluster
      # - bootstrap.memory_lock=true
      - discovery.type=single-node
    mem_limit: 2048m
    volumes:
      - /data/es1/data:/usr/share/elasticsearch/data # it needs permission for others like (777) for tests
      #- elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
      - 9300:9300