version: '3'
services:
  gluster-0:
    image: defreitas/gluster
    build:
      context: .
      dockerfile: gluster.Dockerfile
    hostname: gluster-0.dev
    environment: 
      - SERVER=gluster-1.dev
    # networks:
    #   - mageddo
    network_mode: bridge
    volumes:
      - /var/lib/mageddo/gluster/default:/var/lib/mageddo/gluster/default
    privileged: true

  gluster-1:
    image: defreitas/gluster
    build:
      context: .
      dockerfile: gluster.Dockerfile
    hostname: gluster-1.dev
    environment: 
      - SERVER=gluster-0.dev
    # networks:
    #   - mageddo
    network_mode: bridge
    volumes:
      - /var/lib/mageddo/gluster/default:/var/lib/mageddo/gluster/default
    privileged: true

networks:
  mageddo:
    external: true