version: '3'
services:
  gluster-0:
    build:
      context: .
      dockerfile: gluster.Dockerfile
    command: sudo gluster peer probe gluster-1; tail -f /var/log/glusterfs/nfs.log
    networks:
      - mageddo

  gluster-1:
    build:
      context: .
      dockerfile: gluster.Dockerfile
    command: sudo gluster peer probe gluster-0; tail -f /var/log/glusterfs/nfs.log
    networks:
      - mageddo

networks:
  mageddo:
    external: true