version: '3.6'
services:
  jenkins:
    image: defreitas/jenkins:lts
    build:
      context: .
    volumes:
      - /var/lib/mageddo/data/jenkins/:/var/jenkins_home/
      - /var/run/docker.sock:/var/run/docker.sock

