version: '2'
services:
  jenkins:
    image: jenkins:2.7.4
    container_name: jenkins
    hostname: "jenkins.dev"
    volumes: 
      - /opt/jenkins_home:/var/jenkins_home
    network_mode: bridge
    mem_limit: 500m
    memswap_limit: 0