version: '3.6'
services:
  jenkins:
    image: defreitas/jenkins:2.179-1.0.0
    build:
      context: .
      dockerfile: jenkins.Dockerfile
    volumes:
      - /var/lib/mageddo/data/jenkins/:/var/jenkins_home/
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/docker:/root/.docker
    environment:
      - PTN_CONFIG_DIR=/var/jenkins_home/.portainer-cli
    hostname: jenkins.mageddo.local