version: '3.6'
services:
  jenkins:
    image: defreitas/jenkins:lts
    build:
      context: .
      dockerfile: jenkins.Dockerfile
    ports:
      - 8080:8080
    volumes:
      - /var/lib/docker:/var/lib/docker
      - /home/jenkins/root:/root
      - /home/jenkins/jenkins_home/:/var/jenkins_home/
      - /var/run/docker.sock:/var/run/docker.sock

