# https://hub.docker.com/r/wurstmeister/kafka/tags/
# 9999 - JMX zookeeper
# 9998 - JMX kafka
# docker-compose -f kafka.yml up -d stg-kafka stg-kafka-2
version: '2.2'
services:
  kafka-zookeeper:
    build: 
      context: .
      dockerfile: kafka.Dockerfile
    image: defreitas/kafka:2.1.0
    container_name: kafka
    network_mode: bridge
    hostname: kafka.dev
    mem_limit: 150m
    memswap_limit: 0
    volumes:
      - ./kafka/config/:/opt/kafka/config
      - /etc/resolv.conf:/etc/resolv.conf
    healthcheck:
      test: [CMD, "echo", "0"]
      interval: 3s
#      interval: 1m30s
      timeout: 10s
      retries: 3
    environment:
      - HOSTNAMES=kafka.intranet,zookeeper.intranet

  stg-kafka:
    extends: kafka-zookeeper
    container_name: stg-kafka
    hostname: stg-kafka-1.intranet
    volumes:
      - /opt/databases/stg//kafka/logging:/opt/kafka/logs/
      - /opt/databases/stg/kafka/logs/:/tmp/kafka-logs
      - /opt/databases/stg/zookeeper/logs/:/tmp/zookeeper
    environment:
      - HOSTNAMES=kafka.intranet,zookeeper.intranet

  stg-kafka-2:
    extends: kafka-zookeeper
    environment:
      - HOSTNAMES=kafka-2.intranet
      - JMX_PORT=10001
    hostname: stg-kafka-2.intranet
    container_name: stg-kafka-2
    volumes:
      - ./kafka/supervisord-kafka-2.conf:/etc/supervisor/conf.d/supervisord.conf
      - /opt/databases/stg/kafka-2/logging:/opt/kafka/logs/
      - /opt/databases/stg/kafka-2/logs/:/tmp/kafka-logs
    

  prod-kafka:
    extends: kafka-zookeeper
    container_name: prod-kafka
    volumes:
      - /opt/databases/prod/kafka/logging:/opt/kafka/logs/
      - /opt/databases/prod/kafka/logs/:/tmp/kafka-logs
      - /opt/databases/prod/zookeeper/logs/:/tmp/zookeeper
    hostname: kafka.prod

  stg-kafka-1-0:
    build: 
      context: .
      dockerfile: kafka_1_0_0.Dockerfile
    image: defreitas/kafka:1.0.0
    network_mode: bridge
    mem_limit: 500m
    memswap_limit: 0
    volumes:
      - ./kafka/config/:/opt/kafka/config
      - /etc/resolv.conf:/etc/resolv.conf
    environment:
      - HOSTNAMES=kafka.intranet,zookeeper.intranet
    volumes:
      - /opt/databases/stg/kafka-1.0.0/logging:/opt/kafka/logs/
      - /opt/databases/stg/kafka-1.0.0/logs/:/tmp/kafka-logs
      - /opt/databases/stg/kafka-1.0.0/zookeeper/logs/:/tmp/zookeeper
    environment:
      - HOSTNAMES=kafka.intranet,zookeeper.intranet