# https://hub.docker.com/r/spotify/kafka/
# docker run -p 2181:2181 -p 9092:9092 --env ADVERTISED_HOST=`docker-machine ip \`docker-machine active\`` --env ADVERTISED_PORT=9092 spotify/kafka
version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:0.10.2.0
    container_name: kafka
    # hostname: kafka.dev
    # network_mode: bridge
    # volumes:
      # - /opt/queue/kafka/:/data/kafka
      # - /var/log/kafka/:/var/log/kafka
      # - kafka/kafka.xml:/opt/kafka/conf/kafka.xml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181