# https://hub.docker.com/r/wurstmeister/kafka/tags/
version: '2'
services:
  kafka:
    build: 
      context: .
      dockerfile: kafka.Dockerfile
    image: defreitas/kafka:1.0.0
    container_name: kafka
    links:
      - zookeeper
    command: bin/kafka-server-start.sh config/server.properties
    network_mode: bridge
    hostname: kafka.dev
    mem_limit: 2048m
    memswap_limit: 0
    volumes:
      - ./kafka/config/:/opt/kafka/config
      - /opt/databases/kafka/logs/:/opt/kafka/logs/

  zookeeper:
    build: 
      context: .
      dockerfile: kafka.Dockerfile
    image: defreitas/kafka:1.0.0
    container_name: zookeeper
    hostname: zookeeper.dev
    command: bin/zookeeper-server-start.sh config/zookeeper.properties
    network_mode: bridge
    mem_limit: 1024m
    memswap_limit: 0
    volumes:
      - ./kafka/config/:/opt/kafka/config
      - /opt/databases/zookeeper/logs/:/opt/kafka/logs/

