# https://hub.docker.com/r/wurstmeister/kafka/tags/
version: '2.2'
services:
  kafka-zookeeper:
    build: 
      context: .
      dockerfile: kafka.Dockerfile
    image: defreitas/kafka:1.0.0
    container_name: kafka
    network_mode: bridge
    hostname: kafka.dev
    mem_limit: 2048m
    memswap_limit: 0
    volumes:
      - ./kafka/config/:/opt/kafka/config
    healthcheck:
      test: [CMD, "echo", "0"]
      interval: 3s
#      interval: 1m30s
      timeout: 10s
      retries: 3
    ports:
      - 9092:9092
      - 2181:2181
    environment:
      - HOSTNAMES=kafka.intranet
  stg-kafka:
    container_name: stg-kafka
    depends_on: 
      - kafka-manager
    extends: kafka-zookeeper
    volumes:
      - /opt/databases/kafka-stg/logs/:/tmp/kafka-logs
  prod-kafka:
    container_name: prod-kafka
    depends_on: 
      - kafka-manager
    extends: kafka-zookeeper
    volumes:
      - /opt/databases/kafka-prod/logs/:/tmp/kafka-logs
    hostname: kafka.prod

  kafka-manager:
    image: sheepkiller/kafka-manager
    ports:
      - 9000:9000
    environment:
      - ZK_HOSTS=kafka.intranet:2181
      - APPLICATION_SECRET=admin
    hostname: kafka-manager.dev
