version: '3'
services:
  kafka:
    build:
      context: kafka-2
      dockerfile: Dockerfile
    volumes:
      - /opt/databases/stg/kafka-2/data/:/tmp/kafka-logs
      - /opt/databases/stg/kafka-2/zookeeper/data/:/tmp/zookeeper
    hostname: kafka.intranet
    network_mode: bridge
    environment:
      - KAFKA_HEAP_OPTS=-Xmx700m -Xms200m