# https://hub.docker.com/r/wurstmeister/kafka/tags/
version: '2'
services:
  kafka:
    build: 
      context: .
      dockerfile: kafka
    image: defreitas/kafka:0.10.2.1
    container_name: kafka
    links:
      - zookeeper
    command: bin/kafka-server-start.sh config/server.properties
    network_mode: bridge
    hostname: kafka.dev
    volumes:
      - $PWD/kafkaf/config/:/opt/kafka/config
  zookeeper:
    build: 
      context: .
      dockerfile: kafka
    image: defreitas/kafka:0.10.2.1
    container_name: zookeeper
    command: bin/zookeeper-server-start.sh config/zookeeper.properties
    network_mode: bridge