version: '2'
services:
  lenses:
    image: landoop/lenses
    environment:
      LENSES_PORT: 9991
      LENSES_KAFKA_BROKERS: "PLAINTEXT://kafka.dev:9092"
      LENSES_ZOOKEEPER_HOSTS: "kafka.dev:2181"
      LENSES_SCHEMA_REGISTRY_URLS: "http://schema.registry.1.url:8081,http://schema.registry.2.url:8081"
      LENSES_CONNECT_CLUSTERS: '[{name: "production", url: "http://connect.worker.1.url:8083,http://connect.worker.2.url:8083", statuses: "connect-statuses", configs: "connect-configs", offsets: "connect-offsets"}]'
      LENSES_JMX_ZOOKEEPERS: "kafka.dev:9585"
      LENSES_JMX_CONNECT: '[{production: "connect.worker.1.url:9584,connect.worker.2.url:9584,connect.worker.3.url:9584"}]'
      LENSES_SECURITY_MODE: BASIC
      # Secrets can also be passed as files. Check _examples/
      LENSES_SECURITY_USERS: |
        [
          {"username": "admin", "password": "admin", "displayname": "Lenses Admin", "roles": ["admin", "write", "read"]},
          {"username": "writer", "password": "writer", "displayname": "Lenses Writer", "roles": ["read", "write"]},
          {"username": "reader", "password": "reader", "displayname": "Lenses Reader", "roles": ["read"]},
          {"username": "nodata", "password": "nodata", "displayname": "Lenses NoData", "roles": ["nodata"]}
        ]
    ports:
      - 9991:9991
    volumes:
      - ./license.json:/license.json
    # This is only need in some cases, where you run docker on a server that also hosts a service from the Kafka cluster
    network_mode: bridge