# jdbc URL - jdbc:mysql://mysql-server.dev:3306/
#
# from  terminal -  mysql -h127.0.0.1 -u root --password=root 

version: '2'
services:
  mysql57:
    image: mysql:5.7
    container_name: mysql57
    hostname: mysql-server5.dev
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - /opt/databases/mysql5/data:/var/lib/mysql
      - ./mysql/5/conf.d:/etc/mysql/conf.d

  mysql80:
    image: mysql:8.0.3
    container_name: mysql80
    hostname: mysql-server8.dev
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - /opt/databases/mysql8/data:/var/lib/mysql
      - ./mysql/8/conf.d:/etc/mysql/conf.d