#!/bin/bash

USER_NAME=root
PASSWORD=root
DATA_PATH=/opt/databases/mysql/data

docker run --name mysql-server --hostname mysql-server.dev -p 3306:3306 \
        -e MYSQL_ROOT_PASSWORD=$PASSWORD -d \
	-v $DATA_PATH:/var/lib/mysql mysql


