#!/bin/bash

# jdbc:mysql://mysql-server.dev:3306/

USER_NAME=root
PASSWORD=root
DATA_PATH=/opt/databases/mysql/data
CONTAINER=mysql-server

docker rm -f $CONTAINER
docker run --name $CONTAINER --hostname mysql-server.dev -p 3306:3306 \
        -e MYSQL_ROOT_PASSWORD=$PASSWORD -d \
	-v $DATA_PATH:/var/lib/mysql -v /opt/databases/mysql/conf.d:/etc/mysql/conf.d mysql:5.5


