version: '2'
services:
  nginx:
    image: nginx:1.12
    # ports:
      # - 80:80
      #- 443:443
    hostname: nginx.mageddo
    environment:
      - HOSTNAMES=acme.mageddo
    volumes:
      - ./nginx/certs/:/data/nginx/certs
      - ./nginx/conf.d/:/etc/nginx/conf.d
    container_name: nginx
    network_mode: bridge