version: '2'
services:
  nginx:
    image: nginx:1.10
    ports:
      #- 80:80
      #- 443:443
    hostname: nginx.mageddo
    environment:
      - HOSTNAMES=nginx.mageddo.com
    volumes:
      - ./nginx/sites-enabled/:/etc/nginx/conf.d
    container_name: mg-nginx
    network_mode: 'bridge'