#!/bin/sh

docker rm -f phpmyadmin
docker run --name phpmyadmin --hostname phpmyadmin.dev \
	-e PMA_HOST=mysql-server.dev \
	-e PMA_PORT=3306 \
	-e PMA_USER=root \
	-e PMA_PASSWORD=root \
	-p $PHPMYADMIN_PORT:80 -e MYSQL_USERNAME=$USER_NAME \
	-d phpmyadmin/phpmyadmin

# enjoy ;)
