version: '2.2'
services:
  stg-postgres:
    image: defreitas/postgres:10.3
    build:
      context: .
      dockerfile: postgres.Dockerfile
    environment:
      - TZ=UTC
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=db
      - HOSTNAMES=postgres
    volumes:
      - /opt/databases/stg/postgresql/10.3/data:/var/lib/postgresql/data
      - /var/lib/mageddo:/var/lib/mageddo
    container_name: stg-postgres
    hostname: postgresql-server.dev
    network_mode: bridge
    mem_limit: 1024m
    memswap_limit: 0
    cpu_count: 1

  prod-postgres:
    image: postgres:10.3
    environment:
      - TZ=UTC
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=db
    volumes:
      - /opt/databases/prod/postgresql/10.3/data:/var/lib/postgresql/data
      - /var/lib/mageddo:/var/lib/mageddo
    container_name: prod-postgres
    hostname: postgresql-server.prod

  ssl-protected-postgres:
    image: postgres:10.3
    environment:
      - TZ=UTC
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=db
    volumes:
      - /opt/databases/stg/postgresql-ssl/10.3/data:/var/lib/postgresql/data
      - ./postgres/certs/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      # - ./postgres/certs/server.key:/var/lib/postgresql/data/server.key
      # - ./postgres/certs/server.crt:/var/lib/postgresql/data/server.crt
    hostname: ssl-postgresql-server.docker

  stg-postgres-11:
    image: postgres:11
    environment:
      - TZ=UTC
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=db
    volumes:
      - /opt/databases/stg/postgresql/11/data:/var/lib/postgresql/data
    container_name: stg-postgres-11
    hostname: postgresql-server-11.dev
    mem_limit: 1024m
    memswap_limit: 0
    cpu_count: 1

# url de conexao jdbc:postgresql://postgresql-server.dev:5432/root