version: '2.2'
services:

  postgres-10-rpp:
    image: defreitas/postgres:10.3
    build:
      context: .
      dockerfile: postgres.Dockerfile
    environment:
      - TZ=UTC
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=db
      - HOSTNAMES=postgres,postgres-10.docker
    volumes:
      - /data/databases/stg/postgresql/10.3/mageddo-rpp/data:/var/lib/postgresql/data
      - /var/lib/mageddo:/var/lib/mageddo
    ports:
       - 5434:5432
    network_mode: bridge
    mem_limit: 1024m
    memswap_limit: 0
    cpu_count: 1

  stg-postgres-10:
    image: defreitas/postgres:10.3
    build:
      context: .
      dockerfile: postgres.Dockerfile
    environment:
      - TZ=UTC
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=db
      - HOSTNAMES=postgres,postgres-10.docker
    volumes:
      - /data/databases/stg/postgresql/10.3/data:/var/lib/postgresql/data
      - /var/lib/mageddo:/var/lib/mageddo
    container_name: stg-postgres
    hostname: postgresql-server.dev
    network_mode: bridge
    mem_limit: 1024m
    memswap_limit: 0
    cpu_count: 1
    ports:
      - 5432:5432
    restart: unless-stopped

  ssl-protected-postgres:
    image: postgres:10.3
    environment:
      - TZ=UTC
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=db
    volumes:
      #- /data/databases/stg/postgresql-ssl/10.3/data:/var/lib/postgresql/data
      - ./postgres/certs/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      # - ./postgres/certs/server.key:/var/lib/postgresql/data/server.key
      # - ./postgres/certs/server.crt:/var/lib/postgresql/data/server.crt
    hostname: ssl-postgresql-server.docker

  stg-postgres-11:
    image: defreitas/postgres:11
    build:
      context: .
      dockerfile: postgres-11.Dockerfile
    environment:
      - TZ=UTC
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=db
      - HOSTNAMES=postgres-11.docker
    volumes:
      - /data/databases/stg/postgresql/11/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: unless-stopped
    network_mode: bridge
    hostname: postgresql-server.dev
    mem_limit: 1024m
    memswap_limit: 0
    cpu_count: 2


# url de conexao jdbc:postgresql://postgresql-server.dev:5432/root
