#!/bin/bash

PASSWORD=root
USER=root
DATA_PATH=/opt/databases/postgresql/data

docker run --name postgresql-server --hostname postgresql-server.dev \
	-e POSTGRES_PASSWORD=$PASSWORD \
	-e POSTGRES_USER=$USER \
	-v $DATA_VOLUME_FOLDER:/var/lib/postgresql/data \
	-d postgres
