#!/bin/bash

PASSWORD=root
USER=root
DATA_PATH=/opt/databases/postgresql/data
CONTAINER=postgresql-server

docker rm -f $CONTAINER
docker run --name $CONTAINER --hostname postgresql-server.dev \
	-e POSTGRES_PASSWORD=$PASSWORD \
	-e POSTGRES_USER=$USER \
	-v $DATA_PATH:/var/lib/postgresql/data \
	-d postgres:9.3
