version: '2.2'
services:
  stg-postgres:
    image: postgres:10.3
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=db
    volumes:
      - /opt/databases/stg/postgresql/10.3/data:/var/lib/postgresql/data
    container_name: stg-postgres
    hostname: postgresql-server.dev
    mem_limit: 1024m
    memswap_limit: 0
    cpu_count: 1

  prod-postgres:
    image: postgres:10.3
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=db
    volumes:
      - /opt/databases/prod/postgresql/10.3/data:/var/lib/postgresql/data
    container_name: prod-postgres
    hostname: postgresql-server.prod

# url de conexao jdbc:postgresql://postgresql-server.dev:5432/root