version: '2.2'
services:

  stg-postgres-10:
    image: defreitas/postgres:10.3
    build:
      context: .
      dockerfile: postgres.Dockerfile
    environment:
      - TZ=UTC
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=db
      - HOSTNAMES=postgres,postgres-10.docker
    volumes:
      - /data/databases/stg/postgresql/10.3/data:/var/lib/postgresql/data
      - /var/lib/mageddo:/var/lib/mageddo
    container_name: stg-postgres
    hostname: postgresql-server.dev
    network_mode: bridge
    mem_limit: 1024m
    memswap_limit: 0
    cpu_count: 1
    ports:
      - 5432:5432
    restart: unless-stopped

  # url de conexao jdbc:postgresql://postgresql-server.dev:5432/root
  stg-postgres-11:
    image: defreitas/postgres:11
    build:
      context: .
      dockerfile: postgres-11.Dockerfile
    environment:
      - TZ=UTC
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=db
      - HOSTNAMES=postgres-11.docker
    volumes:
      - /data/databases/stg/postgresql/11/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: unless-stopped
    network_mode: bridge
    hostname: postgresql-server.dev
    mem_limit: 1024m
    memswap_limit: 0
    cpu_count: 2

  stg-postgres-17:
    image: postgres:17.6
    environment:
      - TZ=UTC
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=db
      - HOSTNAMES=postgres-17.docker
    volumes:
      - /data/databases/stg/postgresql/17/data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    restart: unless-stopped
    network_mode: bridge
    mem_limit: 1024m
    memswap_limit: 0
    cpu_count: 2
    command:
      - postgres
      - -c
      - wal_level=logical
      - -c
      - max_wal_senders=10
      - -c
      - max_replication_slots=10
      - -c
      - wal_keep_size=64MB