version: '3'
services:

  debian-9:
    image: defreitas/tools_graalvm-21_debian-9:0.0.2
    build:
      context: .
      dockerfile: "Dockerfile.debian-9"

  debian-9-aarch64:
    image: defreitas/tools_graalvm-21_debian-9_aarch64:0.0.2
    build:
      context: .
      dockerfile: "Dockerfile.debian-9_aarch64"
    platform: linux/arm64/v8
