FROM arm64v8/debian:9-slim AS BUILDER

RUN mkdir /graalvm &&\
    apt-get update -y &&\
    apt-get install --force-yes -y build-essential libz-dev zlib1g-dev curl &&\
    apt-get clean &&\
    rm -r /tmp/* || true

ENV GRAALVM_URL='https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-22.3.1/graalvm-ce-java19-linux-aarch64-22.3.1.tar.gz'
RUN curl -L $GRAALVM_URL > /tmp/graalvm.tgz &&\
    tar --strip 1 -zxvf /tmp/graalvm.tgz -C /graalvm &&\
    /graalvm/bin/gu install native-image &&\
    rm -r /tmp/* || true

ENV JAVA_HOME=/graalvm
ENV PATH="${PATH}:$JAVA_HOME/bin"
LABEL GITHUB="https://github.com/mageddo/dockerized-database-servers/tree/master/_hub/graalvm"