version: '3'
services:
  build:
    build:
      context: .
    image: defreitas/tools-generic-cd:0.1.2
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/lib/docker:/var/lib/docker"